// AUTO-GENERATED — vendored from codex-cli's `codex app-server generate-ts`.
// CLI version: codex-cli 0.145.0 (pinned to 0.145.0 in scripts/generate-codex-types.ts)
// Generated: 2026-07-23
// Regenerate via `bun scripts/generate-codex-types.ts`; version bumps are
// deliberate manual updates, not run automatically on every build.

// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { WebSearchAction } from "./v2/WebSearchAction";

export type WebSearchItem = { id: string, query: string, action: WebSearchAction | null,
/**
 * Structured search results returned out-of-band by standalone web search.
 *
 * These stay as opaque JSON at the extension/app-server boundary so new
 * result fields and result types can pass through without a Codex release.
 */
results: Array<JsonValue> | null, };
