import {
	type CliRuntimeDrainResult,
	drainCliRuntime,
} from "#/lib/cliUpdateRuntime";
import { parseWslUnc } from "#/lib/paths";
import { runBoundedProcess } from "#/lib/process";
import { loadConfig } from "#/server/config";
import {
	type CliUpdateAction,
	getCliUpdateStatuses,
	resolveCliUpdateAction,
} from "./cliUpdates";

const UPDATE_TIMEOUT_MS = 10 * 60 * 1000;
const MAX_OUTPUT_CHARS = 32_000;

async function availableAction(id: string): Promise<CliUpdateAction> {
	const statuses = await getCliUpdateStatuses({ force: true });
	const status = statuses.find((entry) => entry.id === id);
	if (!status) throw new Error("CLI update target was not found");
	if (!status.available)
		throw new Error(`${status.label} is already up to date`);
	const action = await resolveCliUpdateAction(id);
	if (!action) {
		throw new Error("This CLI must be updated with its original installer");
	}
	return action;
}

async function runUpdateProcess(action: CliUpdateAction): Promise<string> {
	// Windows package-manager shims are .cmd files and require cmd.exe.
	// Update argv is generated by Hlid's typed plans, never browser input.
	const shell =
		process.platform === "win32" &&
		action.command.toLowerCase().endsWith(".cmd");
	const result = await runBoundedProcess(action.command, action.args, {
		timeoutMs: UPDATE_TIMEOUT_MS,
		timeoutError: "CLI update timed out",
		maxOutputChars: MAX_OUTPUT_CHARS,
		shell,
	});
	if (result.code !== 0) {
		const detail = result.output.trim().split(/\r?\n/).slice(-4).join(" ");
		throw new Error(
			detail
				? `CLI update exited ${result.code}: ${detail}`
				: `CLI update exited ${result.code}`,
		);
	}
	return result.output.trim();
}

export type PreparedCliUpdate = CliRuntimeDrainResult & {
	command: string;
	mode: "automatic" | "interactive";
	terminalCwd: string;
};

function terminalCwdForUpdate(id: string): string {
	const config = loadConfig();
	const match = id.match(/^wsl:([A-Za-z0-9._-]+):(codex|claude)$/);
	if (!match) return config.vault.path;

	const distro = match[1].toLowerCase();
	const configuredPaths = [
		...(config.agents ?? []).map((agent) => agent.path),
		config.vault.path,
	];
	const cwd = configuredPaths.find(
		(path) => parseWslUnc(path)?.distro.toLowerCase() === distro,
	);
	if (!cwd) {
		throw new Error(`No configured workspace found for WSL distro ${match[1]}`);
	}
	return cwd;
}

export async function prepareCliUpdate(id: string): Promise<PreparedCliUpdate> {
	const action = await availableAction(id);
	const terminalCwd = terminalCwdForUpdate(id);
	const drained = await drainCliRuntime();
	return {
		...drained,
		command: action.displayCommand,
		mode: action.automatic ? "automatic" : "interactive",
		terminalCwd,
	};
}

export async function applyCliUpdate(id: string): Promise<{
	command: string;
	output: string;
	drained: CliRuntimeDrainResult;
}> {
	const action = await availableAction(id);
	if (!action.automatic) {
		throw new Error(
			action.requiresElevation
				? "This update needs an interactive sudo prompt"
				: "This update must be run interactively",
		);
	}
	const drained = await drainCliRuntime();
	const output = await runUpdateProcess(action);
	await getCliUpdateStatuses({ force: true });
	return { command: action.displayCommand, output, drained };
}
