// @vitest-environment jsdom

import { afterEach, describe, expect, it } from "vitest";
import {
	projectPreviewRefElementExpression,
	projectPreviewSemanticSnapshotExpression,
} from "./projectPreviewCdp";

afterEach(() => {
	document.body.replaceChildren();
});

function evaluatePreviewExpression<T>(expression: string): T {
	// biome-ignore lint/security/noGlobalEval: executes only Preview expressions generated by this module in isolated jsdom
	return window.eval(expression) as T;
}

describe("Project Preview semantic references", () => {
	it("tracks visible elements without mutating the app DOM", () => {
		document.body.innerHTML = '<button aria-label="Run task">Run</button>';
		const button = document.querySelector("button");
		if (!button) throw new Error("Expected test button.");
		button.getBoundingClientRect = () =>
			({
				x: 12,
				y: 24,
				top: 24,
				right: 112,
				bottom: 64,
				left: 12,
				width: 100,
				height: 40,
				toJSON: () => ({}),
			}) as DOMRect;

		const elements = evaluatePreviewExpression<
			Array<{ ref: string; role: string; name: string }>
		>(projectPreviewSemanticSnapshotExpression(10));

		expect(elements).toEqual([
			expect.objectContaining({
				ref: "e1",
				role: "button",
				name: "Run task",
			}),
		]);
		expect(button.hasAttribute("data-hlid-preview-ref")).toBe(false);
		expect(
			evaluatePreviewExpression<Element | null>(
				projectPreviewRefElementExpression("e1"),
			),
		).toBe(button);

		button.remove();
		expect(
			evaluatePreviewExpression<Element | null>(
				projectPreviewRefElementExpression("e1"),
			),
		).toBeNull();
	});
});
