// AUTO-GENERATED by scripts/bundle-pty-assets.ts - do not edit manually.
// Regenerated by CI (windows-latest) before bun build --compile.

import f_src_server_pty_worker_cjs from "./pty-embed-assets/d96ad55e31c6-pty-worker_cjs.asset" with { type: "file" };
import f_node_modules_node_pty_package_json from "./pty-embed-assets/e5718707798c-package_json.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_pty_node from "./pty-embed-assets/879ec3316b1d-pty_node.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_conpty_node from "./pty-embed-assets/5249918f4361-conpty_node.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_conpty_console_list_node from "./pty-embed-assets/9d261873bc7c-conpty_console_list_node.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_winpty_agent_exe from "./pty-embed-assets/1db0e771e7a7-winpty-agent_exe.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_winpty_dll from "./pty-embed-assets/c64741cea1ef-winpty_dll.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_conpty_OpenConsole_exe from "./pty-embed-assets/8c65be291285-OpenConsole_exe.asset" with { type: "file" };
import f_node_modules_node_pty_prebuilds_win32_x64_conpty_conpty_dll from "./pty-embed-assets/4036a5ef0fb2-conpty_dll.asset" with { type: "file" };
import f_node_modules_node_pty_lib_windowsPtyAgent_js from "./pty-embed-assets/5d1ebe86dd06-windowsPtyAgent_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_windowsTerminal_js from "./pty-embed-assets/53804d328ea0-windowsTerminal_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_windowsConoutConnection_js from "./pty-embed-assets/34d2a00fa0b7-windowsConoutConnection_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_conpty_console_list_agent_js from "./pty-embed-assets/71eba82a924b-conpty_console_list_agent_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_eventEmitter2_js from "./pty-embed-assets/bc5103985540-eventEmitter2_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_unixTerminal_js from "./pty-embed-assets/9fa0250938c0-unixTerminal_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_index_js from "./pty-embed-assets/68e12a0c4fa7-index_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_types_js from "./pty-embed-assets/63a094f53e28-types_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_interfaces_js from "./pty-embed-assets/1ba7112b8727-interfaces_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_utils_js from "./pty-embed-assets/2470f81c80fc-utils_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_terminal_js from "./pty-embed-assets/ab9c88375a9a-terminal_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_shared_conout_js from "./pty-embed-assets/3cbef647d3cf-conout_js.asset" with { type: "file" };
import f_node_modules_node_pty_lib_worker_conoutSocketWorker_js from "./pty-embed-assets/3154e2f4de21-conoutSocketWorker_js.asset" with { type: "file" };

export const PTY_ASSETS_HASH = "167d9354e808c0747d927f7b3748ad5fe9fb5278f5cc704133bffca64ad770dd";

export const PTY_ASSETS = {
	workerCjs: f_src_server_pty_worker_cjs,
	packageJson: f_node_modules_node_pty_package_json,
	natives: {
		"prebuilds/win32-x64/pty.node": f_node_modules_node_pty_prebuilds_win32_x64_pty_node,
		"prebuilds/win32-x64/conpty.node": f_node_modules_node_pty_prebuilds_win32_x64_conpty_node,
		"prebuilds/win32-x64/conpty_console_list.node": f_node_modules_node_pty_prebuilds_win32_x64_conpty_console_list_node,
		"prebuilds/win32-x64/winpty-agent.exe": f_node_modules_node_pty_prebuilds_win32_x64_winpty_agent_exe,
		"prebuilds/win32-x64/winpty.dll": f_node_modules_node_pty_prebuilds_win32_x64_winpty_dll,
		"prebuilds/win32-x64/conpty/OpenConsole.exe": f_node_modules_node_pty_prebuilds_win32_x64_conpty_OpenConsole_exe,
		"prebuilds/win32-x64/conpty/conpty.dll": f_node_modules_node_pty_prebuilds_win32_x64_conpty_conpty_dll,
	},
	lib: {
		"lib/windowsPtyAgent.js": f_node_modules_node_pty_lib_windowsPtyAgent_js,
		"lib/windowsTerminal.js": f_node_modules_node_pty_lib_windowsTerminal_js,
		"lib/windowsConoutConnection.js": f_node_modules_node_pty_lib_windowsConoutConnection_js,
		"lib/conpty_console_list_agent.js": f_node_modules_node_pty_lib_conpty_console_list_agent_js,
		"lib/eventEmitter2.js": f_node_modules_node_pty_lib_eventEmitter2_js,
		"lib/unixTerminal.js": f_node_modules_node_pty_lib_unixTerminal_js,
		"lib/index.js": f_node_modules_node_pty_lib_index_js,
		"lib/types.js": f_node_modules_node_pty_lib_types_js,
		"lib/interfaces.js": f_node_modules_node_pty_lib_interfaces_js,
		"lib/utils.js": f_node_modules_node_pty_lib_utils_js,
		"lib/terminal.js": f_node_modules_node_pty_lib_terminal_js,
		"lib/shared/conout.js": f_node_modules_node_pty_lib_shared_conout_js,
		"lib/worker/conoutSocketWorker.js": f_node_modules_node_pty_lib_worker_conoutSocketWorker_js,
	},
};
