// Stub — real version auto-generated by scripts/bundle-pty-assets.ts on Windows CI.
// Do NOT edit manually.
export const PTY_ASSETS_HASH = "";
// biome-ignore lint/suspicious/noExplicitAny: generated
export const PTY_ASSETS: any = null;
