import { extname } from "node:path";
import { registerBunServer } from "../lib/lifecycle";
// Static client assets, embedded into the compiled exe via `with { type: "file" }`
// imports. Generated by scripts/embed-client.ts after every `vite build`.
import { EMBEDDED_ASSETS } from "./embedded-client";

const UI_MIME: Record<string, string> = {
	".js": "application/javascript",
	".mjs": "application/javascript",
	".css": "text/css",
	".html": "text/html",
	".json": "application/json",
	".svg": "image/svg+xml",
	".png": "image/png",
	".ico": "image/x-icon",
	".woff": "font/woff",
	".woff2": "font/woff2",
	".webmanifest": "application/manifest+json",
};

function tryUiStatic(pathname: string): Response | null {
	if (pathname === "/" || pathname === "") return null;
	const filePath = EMBEDDED_ASSETS[pathname];
	if (!filePath) return null;
	const headers = new Headers();
	const mime = UI_MIME[extname(pathname).toLowerCase()];
	if (mime) headers.set("content-type", mime);
	return new Response(Bun.file(filePath), { headers });
}

// Only runs from the compiled exe. In dev (`bun run dev:all`), Vite owns
// port 3000 and serves the UI with HMR.
export async function startUiServer(
	port: number,
	bindHost: string,
): Promise<void> {
	// Lazy import — only resolves in the compiled exe after `vite build`.
	// Keeping this dynamic prevents the SSR bundle (and its bundled React)
	// from loading during `bun run dev:server`, which would corrupt React's
	// dispatcher and cause "can't access property 'useContext', dispatcher is null".
	// @ts-expect-error - missing types; Vite produces this at build time
	// fallow-ignore-next-line unresolved-import -- Vite generates this module during the production build.
	const { default: uiHandler } = await import("../../dist/server/server.js");

	// On --restart the old canonical's TCP socket may still be held by the OS
	// briefly after the process exits. Retry until the socket is released.
	const deadline = Date.now() + 30_000;
	while (true) {
		try {
			registerBunServer(
				Bun.serve({
					port,
					hostname: bindHost,
					idleTimeout: 60,
					async fetch(req, srv) {
						const url = new URL(req.url);
						const staticRes = tryUiStatic(url.pathname);
						if (staticRes) return staticRes;
						// h3-v2 expects req.ip (or req.context.clientAddress). Bun surfaces the
						// peer address via server.requestIP; attach it before delegating.
						const peer = srv.requestIP(req)?.address;
						if (peer && !(req as Request & { ip?: string }).ip) {
							Object.defineProperty(req, "ip", {
								value: peer,
								configurable: true,
							});
						}
						return (
							uiHandler as {
								fetch: (r: Request, s: unknown) => Promise<Response>;
							}
						).fetch(req, srv);
					},
				}),
			);
			break;
		} catch (e) {
			if (Date.now() >= deadline) throw e;
			await new Promise((r) => setTimeout(r, 200));
		}
	}
	console.log(`Hlid UI on :${port}`);
}
