// AUTO-GENERATED — vendored from codex-cli's `codex app-server generate-ts`.
// CLI version: codex-cli 0.145.0 (pinned to 0.145.0 in scripts/generate-codex-types.ts)
// Generated: 2026-07-23
// Regenerate via `bun scripts/generate-codex-types.ts`; version bumps are
// deliberate manual updates, not run automatically on every build.

// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivePermissionProfile = {
/**
 * Identifier from `default_permissions` or the implicit built-in default,
 * such as `:workspace` or a user-defined `[permissions.<id>]` profile.
 */
id: string,
/**
 * Parent profile identifier from the selected permissions profile's
 * `extends` setting, when present.
 */
extends: string | null, };
