// AUTO-GENERATED — vendored from codex-cli's `codex app-server generate-ts`.
// CLI version: codex-cli 0.144.4 (pinned to 0.144.4 in scripts/generate-codex-types.ts)
// Generated: 2026-07-15
// Regenerate via `bun scripts/generate-codex-types.ts`; version bumps are
// deliberate manual updates, not run automatically on every build.

// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpElicitationObjectType } from "./McpElicitationObjectType";
import type { McpElicitationPrimitiveSchema } from "./McpElicitationPrimitiveSchema";

/**
 * Typed form schema for MCP `elicitation/create` requests.
 *
 * This matches the `requestedSchema` shape from the MCP 2025-11-25
 * `ElicitRequestFormParams` schema.
 */
export type McpElicitationSchema = { $schema?: string, type: McpElicitationObjectType, properties: { [key in string]?: McpElicitationPrimitiveSchema }, required?: Array<string>, };
