// AUTO-GENERATED — vendored from codex-cli's `codex app-server generate-ts`.
// CLI version: codex-cli 0.145.0 (pinned to 0.145.0 in scripts/generate-codex-types.ts)
// Generated: 2026-07-23
// Regenerate via `bun scripts/generate-codex-types.ts`; version bumps are
// deliberate manual updates, not run automatically on every build.

// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { McpServerElicitationAction } from "./McpServerElicitationAction";

export type McpServerElicitationRequestResponse = { action: McpServerElicitationAction,
/**
 * Structured user input for accepted elicitations, mirroring RMCP `CreateElicitationResult`.
 *
 * This is nullable because decline/cancel responses have no content.
 */
content: JsonValue | null,
/**
 * Optional client metadata for form-mode action handling.
 */
_meta: JsonValue | null, };
