/**
 * bundle-pty-assets.ts — run on Windows CI before `bun build --compile`.
 *
 * Finds all node-pty runtime files (worker, natives, lib JS) and generates
 * src/server/pty-assets.ts with Bun `with { type: "file" }` asset imports
 * so the compiled hlid.exe can extract them at runtime.
 *
 * Usage: bun scripts/bundle-pty-assets.ts
 */

import {
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { join, relative } from "node:path";

// ── Repo root ────────────────────────────────────────────────────────────────
const repoRoot = join(import.meta.dir, "..");
const outFile = join(repoRoot, "src/server/pty-assets.ts");

// ── Files to embed ───────────────────────────────────────────────────────────

/** Relative to repo root → destination key used in PTY_ASSETS */
const STATIC_ENTRIES: Array<{ repoRel: string; destKey: string; category: "special" | "native" | "lib" }> = [
	{
		repoRel: "src/server/pty-worker.cjs",
		destKey: "workerCjs",
		category: "special",
	},
	{
		repoRel: "node_modules/node-pty/package.json",
		destKey: "packageJson",
		category: "special",
	},
];

/** Native binaries — also hashed for cache invalidation */
const NATIVE_FILES = [
	"node_modules/node-pty/prebuilds/win32-x64/pty.node",
	"node_modules/node-pty/prebuilds/win32-x64/conpty.node",
	"node_modules/node-pty/prebuilds/win32-x64/conpty_console_list.node",
	"node_modules/node-pty/prebuilds/win32-x64/winpty-agent.exe",
	"node_modules/node-pty/prebuilds/win32-x64/winpty.dll",
	"node_modules/node-pty/prebuilds/win32-x64/conpty/OpenConsole.exe",
	"node_modules/node-pty/prebuilds/win32-x64/conpty/conpty.dll",
];

/** Directories to scan for non-test JS files */
const LIB_SCAN_DIRS = [
	"node_modules/node-pty/lib",
	"node_modules/node-pty/lib/shared",
	"node_modules/node-pty/lib/worker",
];

// ── Sanitize a path to a valid TS identifier (f_ prefix) ────────────────────
function toIdent(repoRelPath: string): string {
	return "f_" + repoRelPath.replace(/[^a-zA-Z0-9]/g, "_");
}

// ── Collect lib JS files ─────────────────────────────────────────────────────
function collectLibFiles(): string[] {
	const files: string[] = [];
	for (const dir of LIB_SCAN_DIRS) {
		const absDir = join(repoRoot, dir);
		let entries: string[];
		try {
			entries = readdirSync(absDir);
		} catch {
			continue;
		}
		for (const name of entries) {
			if (!name.endsWith(".js")) continue;
			if (name.endsWith(".test.js") || name.endsWith(".map")) continue;
			const absPath = join(absDir, name);
			if (statSync(absPath).isFile()) {
				files.push(join(dir, name).replace(/\\/g, "/"));
			}
		}
	}
	return files;
}

// ── Compute hash over native binary contents (sorted by dest path) ───────────
function computeHash(nativeRepoPaths: string[]): string {
	// Sort for deterministic ordering
	const sorted = [...nativeRepoPaths].sort();
	const hash = createHash("sha256");
	for (const repoRel of sorted) {
		const absPath = join(repoRoot, repoRel);
		hash.update(readFileSync(absPath));
	}
	return hash.digest("hex");
}

// ── Build import path (relative to src/server/) ──────────────────────────────
function toImportPath(repoRelPath: string): string {
	// src/server/pty-assets.ts → need path from src/server/ to the file
	const srcServerDir = join(repoRoot, "src/server");
	const abs = join(repoRoot, repoRelPath);
	// Use POSIX-style slashes
	return "./" + relative(srcServerDir, abs).replace(/\\/g, "/");
}

// ── Destination key for natives map ─────────────────────────────────────────
function nativeDestKey(repoRel: string): string {
	// Strip "node_modules/node-pty/" prefix → e.g. "prebuilds/win32-x64/pty.node"
	return repoRel.replace(/^node_modules\/node-pty\//, "");
}

// ── Destination key for lib map ──────────────────────────────────────────────
function libDestKey(repoRel: string): string {
	// Strip "node_modules/node-pty/" prefix → e.g. "lib/index.js"
	return repoRel.replace(/^node_modules\/node-pty\//, "");
}

// ── Main ─────────────────────────────────────────────────────────────────────

const libFiles = collectLibFiles();
const nativeRepoRels = NATIVE_FILES;
const hash = computeHash(nativeRepoRels);

// Build all import entries: [ident, repoRel]
const importEntries: Array<{ ident: string; repoRel: string }> = [];

// Special (workerCjs, packageJson)
for (const entry of STATIC_ENTRIES) {
	importEntries.push({ ident: toIdent(entry.repoRel), repoRel: entry.repoRel });
}

// Natives
for (const repoRel of nativeRepoRels) {
	importEntries.push({ ident: toIdent(repoRel), repoRel });
}

// Lib files
for (const repoRel of libFiles) {
	importEntries.push({ ident: toIdent(repoRel), repoRel });
}

// ── Generate source ──────────────────────────────────────────────────────────

const lines: string[] = [
	"// AUTO-GENERATED by scripts/bundle-pty-assets.ts — do not edit manually.",
	"// Regenerated by CI (windows-latest) before bun build --compile.",
	"",
];

// Import statements
for (const { ident, repoRel } of importEntries) {
	const importPath = toImportPath(repoRel);
	lines.push(`import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`);
}

lines.push("");
lines.push(`export const PTY_ASSETS_HASH = ${JSON.stringify(hash)};`);
lines.push("");

// PTY_ASSETS object
lines.push("export const PTY_ASSETS = {");

// workerCjs
const workerIdent = toIdent("src/server/pty-worker.cjs");
lines.push(`\tworkerCjs: ${workerIdent},`);

// packageJson
const pkgIdent = toIdent("node_modules/node-pty/package.json");
lines.push(`\tpackageJson: ${pkgIdent},`);

// natives
lines.push("\tnatives: {");
for (const repoRel of nativeRepoRels) {
	const ident = toIdent(repoRel);
	const key = nativeDestKey(repoRel);
	lines.push(`\t\t${JSON.stringify(key)}: ${ident},`);
}
lines.push("\t},");

// lib
lines.push("\tlib: {");
for (const repoRel of libFiles) {
	const ident = toIdent(repoRel);
	const key = libDestKey(repoRel);
	lines.push(`\t\t${JSON.stringify(key)}: ${ident},`);
}
lines.push("\t},");

lines.push("};");
lines.push("");

const source = lines.join("\n");
writeFileSync(outFile, source, "utf8");

console.log(`Wrote ${outFile}`);
console.log(`  PTY_ASSETS_HASH = ${hash}`);
console.log(`  Natives: ${nativeRepoRels.length}`);
console.log(`  Lib files: ${libFiles.length}`);
