import { createHash } from "node:crypto";
import {
	copyFileSync,
	existsSync,
	mkdtempSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join, relative } from "node:path";

const root = join(import.meta.dir, "..");
const vendor = join(root, "vendor", "whisper");
const generatedDir = join(root, "build", "embed-assets", "whisper");
const stagedDir = join(generatedDir, "files");
const outFile = join(generatedDir, "voice-assets.generated.js");
const WHISPER_VERSION = "v1.8.6";
const WHISPER_ARCHIVE_URL = `https://github.com/ggml-org/whisper.cpp/releases/download/${WHISPER_VERSION}/whisper-bin-x64.zip`;

function walk(dir: string, prefix = ""): string[] {
	return readdirSync(dir).flatMap((name) => {
		const absolute = join(dir, name);
		const rel = join(prefix, name);
		return statSync(absolute).isDirectory() ? walk(absolute, rel) : [rel];
	});
}

async function ensureRuntime(): Promise<void> {
	const alreadyPresent =
		existsSync(vendor) &&
		walk(vendor).some(
			(file) => basename(file).toLowerCase() === "whisper-server.exe",
		);
	if (alreadyPresent) return;

	console.log(`Downloading whisper.cpp ${WHISPER_VERSION} CPU runtime...`);
	const temp = mkdtempSync(join(tmpdir(), "hlid-whisper-"));
	const archive = join(temp, "whisper-bin-x64.zip");
	try {
		const response = await fetch(WHISPER_ARCHIVE_URL);
		if (!response.ok) {
			throw new Error(`runtime download failed: HTTP ${response.status}`);
		}
		await Bun.write(archive, await response.arrayBuffer());
		const commands =
			process.platform === "win32"
				? [
						["tar", "-xf", archive, "-C", vendor],
						["unzip", "-q", archive, "-d", vendor],
					]
				: [
						["unzip", "-q", archive, "-d", vendor],
						["tar", "-xf", archive, "-C", vendor],
					];
		let extracted = false;
		for (const command of commands) {
			rmSync(vendor, { recursive: true, force: true });
			mkdirSync(vendor, { recursive: true });
			try {
				const process = Bun.spawn(command, {
					stdout: "ignore",
					stderr: "ignore",
				});
				if ((await process.exited) === 0) {
					extracted = true;
					break;
				}
			} catch {
				// Try the next platform extractor.
			}
		}
		if (!extracted) {
			throw new Error("failed to extract whisper runtime with unzip or tar");
		}
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
}

await ensureRuntime();

const files = walk(vendor).filter((file) => /\.(exe|dll)$/i.test(file));
if (!files.some((file) => basename(file).toLowerCase() === "whisper-server.exe")) {
	throw new Error("vendor/whisper does not contain whisper-server.exe");
}
rmSync(generatedDir, { recursive: true, force: true });
mkdirSync(stagedDir, { recursive: true });
const hash = createHash("sha256");
const entries = files.map((file, index) => {
	const bytes = readFileSync(join(vendor, file));
	hash.update(file).update(bytes);
	const staged = join(stagedDir, `${index}-${basename(file)}.asset`);
	copyFileSync(join(vendor, file), staged);
	return { file: basename(file), staged, ident: `asset_${index}` };
});
const lines = ["// AUTO-GENERATED by scripts/bundle-whisper-assets.ts", ""];
for (const entry of entries) {
	const importPath = `./${relative(generatedDir, entry.staged).replaceAll("\\", "/")}`;
	lines.push(`import ${entry.ident} from ${JSON.stringify(importPath)} with { type: "file" };`);
}
lines.push("", `export const WHISPER_ASSETS_HASH = ${JSON.stringify(hash.digest("hex"))};`, "", "export const WHISPER_ASSETS = {");
for (const entry of entries) lines.push(`\t${JSON.stringify(entry.file)}: ${entry.ident},`);
lines.push("};", "");
writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`Bundled ${entries.length} whisper runtime files`);
console.log(`Wrote ${outFile}`);
