/**
 * bundle-pty-assets.ts - run on Windows CI before `bun build --compile`.
 *
 * Finds all node-pty runtime files (worker, natives, lib JS), copies them to
 * neutral generated asset names, and generates src/server/pty-assets.ts with
 * Bun `with { type: "file" }` imports so the compiled hlid.exe can extract
 * them at runtime.
 *
 * The neutral asset copy matters: importing .node files directly, even with
 * `type: "file"`, can be treated as a Node-API module load by Bun and crash
 * the compiled exe before our startup logger is active.
 *
 * Usage: bun scripts/bundle-pty-assets.ts
 */

import { createHash } from "node:crypto";
import {
	copyFileSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { basename, join, relative } from "node:path";

const repoRoot = join(import.meta.dir, "..");
const srcServerDir = join(repoRoot, "src/server");
const outFile = join(srcServerDir, "pty-assets.ts");
const stagedDir = join(srcServerDir, "pty-embed-assets");
const NODE_PTY_PREFIX = "node_modules/node-pty/";

type StaticEntry = {
	repoRel: string;
	destKey: "workerCjs" | "packageJson";
};

const STATIC_ENTRIES: StaticEntry[] = [
	{
		repoRel: "src/server/pty-worker.cjs",
		destKey: "workerCjs",
	},
	{
		repoRel: "node_modules/node-pty/package.json",
		destKey: "packageJson",
	},
];

/** Native binaries - also hashed for cache invalidation. */
const NATIVE_FILES = [
	"node_modules/node-pty/prebuilds/win32-x64/pty.node",
	"node_modules/node-pty/prebuilds/win32-x64/conpty.node",
	"node_modules/node-pty/prebuilds/win32-x64/conpty_console_list.node",
	"node_modules/node-pty/prebuilds/win32-x64/winpty-agent.exe",
	"node_modules/node-pty/prebuilds/win32-x64/winpty.dll",
	"node_modules/node-pty/prebuilds/win32-x64/conpty/OpenConsole.exe",
	"node_modules/node-pty/prebuilds/win32-x64/conpty/conpty.dll",
];

/** Directories to scan for non-test JS files. */
const LIB_SCAN_DIRS = [
	"node_modules/node-pty/lib",
	"node_modules/node-pty/lib/shared",
	"node_modules/node-pty/lib/worker",
];

function slash(p: string): string {
	return p.replaceAll(String.fromCharCode(92), "/");
}

function toIdent(repoRelPath: string): string {
	return "f_" + repoRelPath.replace(/[^a-zA-Z0-9]/g, "_");
}

function collectLibFiles(): string[] {
	const files: string[] = [];
	for (const dir of LIB_SCAN_DIRS) {
		const absDir = join(repoRoot, dir);
		let entries: string[];
		try {
			entries = readdirSync(absDir);
		} catch {
			continue;
		}
		for (const name of entries) {
			if (!name.endsWith(".js")) continue;
			if (name.endsWith(".test.js") || name.endsWith(".map")) continue;
			const absPath = join(absDir, name);
			if (statSync(absPath).isFile()) {
				files.push(slash(join(dir, name)));
			}
		}
	}
	return files;
}

function computeHash(nativeRepoPaths: string[]): string {
	const sorted = [...nativeRepoPaths].sort();
	const hash = createHash("sha256");
	for (const repoRel of sorted) {
		const absPath = join(repoRoot, repoRel);
		hash.update(readFileSync(absPath));
	}
	return hash.digest("hex");
}

function toImportPath(repoRelPath: string): string {
	const abs = join(repoRoot, repoRelPath);
	return "./" + slash(relative(srcServerDir, abs));
}

function nodePtyDestKey(repoRel: string): string {
	return repoRel.startsWith(NODE_PTY_PREFIX)
		? repoRel.slice(NODE_PTY_PREFIX.length)
		: repoRel;
}

function stagedRepoRel(repoRel: string): string {
	const hash = createHash("sha256").update(repoRel).digest("hex").slice(0, 12);
	const safeBase = basename(repoRel).replace(/[^a-zA-Z0-9_-]/g, "_");
	return `src/server/pty-embed-assets/${hash}-${safeBase}.asset`;
}

function stageAssets(repoRels: string[]): Map<string, string> {
	rmSync(stagedDir, { recursive: true, force: true });
	mkdirSync(stagedDir, { recursive: true });
	const staged = new Map<string, string>();
	for (const repoRel of repoRels) {
		const stagedRel = stagedRepoRel(repoRel);
		copyFileSync(join(repoRoot, repoRel), join(repoRoot, stagedRel));
		staged.set(repoRel, stagedRel);
	}
	return staged;
}

const libFiles = collectLibFiles();
const nativeRepoRels = NATIVE_FILES;
const hash = computeHash(nativeRepoRels);
const allRepoRels = [
	...STATIC_ENTRIES.map((entry) => entry.repoRel),
	...nativeRepoRels,
	...libFiles,
];
const staged = stageAssets(allRepoRels);

const importEntries = allRepoRels.map((repoRel) => ({
	ident: toIdent(repoRel),
	repoRel,
	stagedRepoRel: staged.get(repoRel),
}));

const lines: string[] = [
	"// AUTO-GENERATED by scripts/bundle-pty-assets.ts - do not edit manually.",
	"// Regenerated by CI (windows-latest) before bun build --compile.",
	"",
];

for (const { ident, repoRel, stagedRepoRel } of importEntries) {
	if (!stagedRepoRel) throw new Error(`Missing staged asset for ${repoRel}`);
	const importPath = toImportPath(stagedRepoRel);
	lines.push(
		`import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`,
	);
}

lines.push("");
lines.push(`export const PTY_ASSETS_HASH = ${JSON.stringify(hash)};`);
lines.push("");
lines.push("export const PTY_ASSETS = {");

const workerIdent = toIdent("src/server/pty-worker.cjs");
lines.push(`	workerCjs: ${workerIdent},`);

const pkgIdent = toIdent("node_modules/node-pty/package.json");
lines.push(`	packageJson: ${pkgIdent},`);

lines.push("	natives: {");
for (const repoRel of nativeRepoRels) {
	const ident = toIdent(repoRel);
	const key = nodePtyDestKey(repoRel);
	lines.push(`		${JSON.stringify(key)}: ${ident},`);
}
lines.push("	},");

lines.push("	lib: {");
for (const repoRel of libFiles) {
	const ident = toIdent(repoRel);
	const key = nodePtyDestKey(repoRel);
	lines.push(`		${JSON.stringify(key)}: ${ident},`);
}
lines.push("	},");
lines.push("};");
lines.push("");

writeFileSync(outFile, lines.join(String.fromCharCode(10)), "utf8");

console.log(`Wrote ${outFile}`);
console.log(`  PTY_ASSETS_HASH = ${hash}`);
console.log(`  Staged assets: ${allRepoRels.length}`);
console.log(`  Natives: ${nativeRepoRels.length}`);
console.log(`  Lib files: ${libFiles.length}`);
