import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");

async function bundleWorker(options: {
	name: string;
	entry: string;
	output: string;
}): Promise<void> {
	const outputPath = resolve(root, options.output);
	const result = await Bun.build({
		entrypoints: [resolve(root, options.entry)],
		target: "bun",
		format: "esm",
		minify: true,
	});
	if (!result.success || result.outputs.length !== 1) {
		for (const log of result.logs) console.error(log);
		throw new Error(`Failed to bundle ${options.name}`);
	}
	const source = await result.outputs[0].text();
	await mkdir(dirname(outputPath), { recursive: true });
	await Bun.write(
		outputPath,
		`// Generated by scripts/bundle-vault-worker.ts. Do not edit.\nexport default ${JSON.stringify(source)};\n`,
	);
	console.log(`Bundled ${options.name} (${source.length} bytes)`);
}

await Promise.all([
	bundleWorker({
		name: "Vault snapshot worker",
		entry: "src/server/vaultSnapshotWorker.ts",
		output: "build/embed-assets/vault/vault-worker-source.generated.ts",
	}),
	bundleWorker({
		name: "Umbod analytics worker",
		entry: "src/server/umbodAnalyticsWorker.ts",
		output:
			"build/embed-assets/umbod/analytics-worker-source.generated.ts",
	}),
]);
