import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const outputPath = resolve(
	root,
	"build/embed-assets/vault/vault-worker-source.generated.ts",
);
const result = await Bun.build({
	entrypoints: [resolve(root, "src/server/vaultSnapshotWorker.ts")],
	target: "bun",
	format: "esm",
	minify: true,
});
if (!result.success || result.outputs.length !== 1) {
	for (const log of result.logs) console.error(log);
	throw new Error("Failed to bundle Vault snapshot worker");
}
const source = await result.outputs[0].text();
await mkdir(dirname(outputPath), { recursive: true });
await Bun.write(
	outputPath,
	`// Generated by scripts/bundle-vault-worker.ts. Do not edit.\nexport default ${JSON.stringify(source)};\n`,
);
console.log(`Bundled Vault snapshot worker (${source.length} bytes)`);
