// Walks dist/client and emits src/server/embedded-client.ts.
// Each file becomes a static `import ... with { type: "file" }` so
// `bun build --compile` bakes the bytes into hlid.exe, no sibling dist
// folder needed at runtime.
//
// Run after `vite build`, before `bun build --compile`.

import { createHash } from "node:crypto";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { posix, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const clientDir = resolve(root, "dist", "client");
const out = resolve(root, "src", "server", "embedded-client.ts");

const banner = `// @ts-nocheck
// AUTO-GENERATED by scripts/embed-client.ts. Do not edit.
// Re-runs every \`bun run build\`. Treat as build artifact.
// Bun \`with { type: "file" }\` imports + content-hashed asset paths confuse
// tsc's bundler resolver; runtime is correct.
`;

// No dist/client yet (fresh checkout, dev mode before first build).
// Emit an empty stub so the import in src/server/index.ts resolves.
if (!existsSync(clientDir)) {
	writeFileSync(out, `${banner}\nexport const EMBEDDED_ASSETS: Record<string, string> = {};\n`);
	console.log("dist/client missing, wrote empty embedded-client.ts stub");
	process.exit(0);
}

function walk(dir: string, base = ""): string[] {
	const entries = readdirSync(dir);
	const files: string[] = [];
	for (const name of entries) {
		const abs = `${dir}/${name}`;
		const rel = base ? posix.join(base, name) : name;
		if (statSync(abs).isDirectory()) {
			files.push(...walk(abs, rel));
		} else {
			files.push(rel);
		}
	}
	return files;
}

// Hash suffix prevents collisions when distinct paths sanitize to the same
// identifier (e.g. "foo-bar.js" and "foo_bar.js" both → "foo_bar_js").
function safeIdent(p: string): string {
	const sanitized = p.replace(/[^a-zA-Z0-9]/g, "_");
	const hash = createHash("sha256").update(p).digest("hex").slice(0, 8);
	return `f_${sanitized}_${hash}`;
}

const files = walk(clientDir).sort();

const importLines: string[] = [];
const mapLines: string[] = [];

for (const rel of files) {
	const ident = safeIdent(rel);
	importLines.push(
		`import ${ident} from "../../dist/client/${rel}" with { type: "file" };`,
	);
	// URL path is "/foo/bar.js", leading slash matches Bun.serve URL.pathname.
	mapLines.push(`\t${JSON.stringify(`/${rel}`)}: ${ident},`);
}

const content = `${banner}
${importLines.join("\n")}

export const EMBEDDED_ASSETS: Record<string, string> = {
${mapLines.join("\n")}
};
`;

writeFileSync(out, content);
console.log(`Embedded ${files.length} client files → src/server/embedded-client.ts`);
