/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as RelicsRouteImport } from './routes/relics'
import { Route as RavenRouteImport } from './routes/raven'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as EinherjarRouteImport } from './routes/einherjar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiBrowseRouteImport } from './routes/api/browse'
import { Route as ApiAttachmentsUploadRouteImport } from './routes/api/attachments/upload'
import { Route as ApiAttachmentsIdRouteImport } from './routes/api/attachments/$id'
import { Route as ApiAttachmentsIdRawRouteImport } from './routes/api/attachments/$id.raw'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const RelicsRoute = RelicsRouteImport.update({
  id: '/relics',
  path: '/relics',
  getParentRoute: () => rootRouteImport,
} as any)
const RavenRoute = RavenRouteImport.update({
  id: '/raven',
  path: '/raven',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const EinherjarRoute = EinherjarRouteImport.update({
  id: '/einherjar',
  path: '/einherjar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowseRoute = ApiBrowseRouteImport.update({
  id: '/api/browse',
  path: '/api/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsUploadRoute = ApiAttachmentsUploadRouteImport.update({
  id: '/api/attachments/upload',
  path: '/api/attachments/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsIdRoute = ApiAttachmentsIdRouteImport.update({
  id: '/api/attachments/$id',
  path: '/api/attachments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsIdRawRoute = ApiAttachmentsIdRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ApiAttachmentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einherjar': typeof EinherjarRoute
  '/forge': typeof ForgeRoute
  '/ledger': typeof LedgerRoute
  '/raven': typeof RavenRoute
  '/relics': typeof RelicsRoute
  '/vault': typeof VaultRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRouteWithChildren
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/attachments/$id/raw': typeof ApiAttachmentsIdRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einherjar': typeof EinherjarRoute
  '/forge': typeof ForgeRoute
  '/ledger': typeof LedgerRoute
  '/raven': typeof RavenRoute
  '/relics': typeof RelicsRoute
  '/vault': typeof VaultRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRouteWithChildren
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/attachments/$id/raw': typeof ApiAttachmentsIdRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einherjar': typeof EinherjarRoute
  '/forge': typeof ForgeRoute
  '/ledger': typeof LedgerRoute
  '/raven': typeof RavenRoute
  '/relics': typeof RelicsRoute
  '/vault': typeof VaultRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRouteWithChildren
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/attachments/$id/raw': typeof ApiAttachmentsIdRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einherjar'
    | '/forge'
    | '/ledger'
    | '/raven'
    | '/relics'
    | '/vault'
    | '/api/browse'
    | '/api/config'
    | '/api/health'
    | '/api/attachments/$id'
    | '/api/attachments/upload'
    | '/api/attachments/$id/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einherjar'
    | '/forge'
    | '/ledger'
    | '/raven'
    | '/relics'
    | '/vault'
    | '/api/browse'
    | '/api/config'
    | '/api/health'
    | '/api/attachments/$id'
    | '/api/attachments/upload'
    | '/api/attachments/$id/raw'
  id:
    | '__root__'
    | '/'
    | '/einherjar'
    | '/forge'
    | '/ledger'
    | '/raven'
    | '/relics'
    | '/vault'
    | '/api/browse'
    | '/api/config'
    | '/api/health'
    | '/api/attachments/$id'
    | '/api/attachments/upload'
    | '/api/attachments/$id/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinherjarRoute: typeof EinherjarRoute
  ForgeRoute: typeof ForgeRoute
  LedgerRoute: typeof LedgerRoute
  RavenRoute: typeof RavenRoute
  RelicsRoute: typeof RelicsRoute
  VaultRoute: typeof VaultRoute
  ApiBrowseRoute: typeof ApiBrowseRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAttachmentsIdRoute: typeof ApiAttachmentsIdRouteWithChildren
  ApiAttachmentsUploadRoute: typeof ApiAttachmentsUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relics': {
      id: '/relics'
      path: '/relics'
      fullPath: '/relics'
      preLoaderRoute: typeof RelicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raven': {
      id: '/raven'
      path: '/raven'
      fullPath: '/raven'
      preLoaderRoute: typeof RavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einherjar': {
      id: '/einherjar'
      path: '/einherjar'
      fullPath: '/einherjar'
      preLoaderRoute: typeof EinherjarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browse': {
      id: '/api/browse'
      path: '/api/browse'
      fullPath: '/api/browse'
      preLoaderRoute: typeof ApiBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/upload': {
      id: '/api/attachments/upload'
      path: '/api/attachments/upload'
      fullPath: '/api/attachments/upload'
      preLoaderRoute: typeof ApiAttachmentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$id': {
      id: '/api/attachments/$id'
      path: '/api/attachments/$id'
      fullPath: '/api/attachments/$id'
      preLoaderRoute: typeof ApiAttachmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$id/raw': {
      id: '/api/attachments/$id/raw'
      path: '/raw'
      fullPath: '/api/attachments/$id/raw'
      preLoaderRoute: typeof ApiAttachmentsIdRawRouteImport
      parentRoute: typeof ApiAttachmentsIdRoute
    }
  }
}

interface ApiAttachmentsIdRouteChildren {
  ApiAttachmentsIdRawRoute: typeof ApiAttachmentsIdRawRoute
}

const ApiAttachmentsIdRouteChildren: ApiAttachmentsIdRouteChildren = {
  ApiAttachmentsIdRawRoute: ApiAttachmentsIdRawRoute,
}

const ApiAttachmentsIdRouteWithChildren =
  ApiAttachmentsIdRoute._addFileChildren(ApiAttachmentsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinherjarRoute: EinherjarRoute,
  ForgeRoute: ForgeRoute,
  LedgerRoute: LedgerRoute,
  RavenRoute: RavenRoute,
  RelicsRoute: RelicsRoute,
  VaultRoute: VaultRoute,
  ApiBrowseRoute: ApiBrowseRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAttachmentsIdRoute: ApiAttachmentsIdRouteWithChildren,
  ApiAttachmentsUploadRoute: ApiAttachmentsUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
